package com.flyworkspace.person.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table "PERSON_INFO".
 */
public class PersonInfo implements Serializable{

    private Long id;
    /** Not-null value. */
    private String companyName;
    private String contactName;
    private String nickname;
    private String sex;
    private String contactPhone;
    private String address;
    private String range;
    private String category;
    private String note;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PersonInfo() {
    }

    public PersonInfo(Long id) {
        this.id = id;
    }

    public PersonInfo(Long id, String companyName, String contactName, String nickname, String sex, String contactPhone, String address, String range, String category, String note) {
        this.id = id;
        this.companyName = companyName;
        this.contactName = contactName;
        this.nickname = nickname;
        this.sex = sex;
        this.contactPhone = contactPhone;
        this.address = address;
        this.range = range;
        this.category = category;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCompanyName() {
        return companyName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getContactPhone() {
        return contactPhone;
    }

    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getRange() {
        return range;
    }

    public void setRange(String range) {
        this.range = range;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
