package com.flyworkspace.person.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.flyworkspace.person.model.PersonInfo;

import com.flyworkspace.person.dao.PersonInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInfoDaoConfig;

    private final PersonInfoDao personInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInfoDaoConfig = daoConfigMap.get(PersonInfoDao.class).clone();
        personInfoDaoConfig.initIdentityScope(type);

        personInfoDao = new PersonInfoDao(personInfoDaoConfig, this);

        registerDao(PersonInfo.class, personInfoDao);
    }
    
    public void clear() {
        personInfoDaoConfig.getIdentityScope().clear();
    }

    public PersonInfoDao getPersonInfoDao() {
        return personInfoDao;
    }

}
